# Generated by Django 4.2.7 on 2023-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('emid', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=5)),
            ],
        ),
    ]
