# Generated by Django 4.2.7 on 2023-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
